server:
  port: 9527  #端口号
spring:
  application:
    name: microServiceCloudGateway
#  cloud:
#    gateway: #网关路由配置
#      routes:
#        #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
#        - id: provider_dept_list_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
#          uri: lb://microServiceCloudProviderDept  #http://localhost:8001  #匹配后提供服务的路由地址  动态路由 此处的uri 改为服务提供者暴露的name
#          predicates:
#            #以下是断言条件，必选全部符合条件
#            - Path=/getAll/**               #断言，路径匹配 注意：Path 中 P 为大写
#            - Method=GET #只能时 GET 请求时，才能访问
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #默认值为 true，即默认开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: provider_dept_list_routh   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://microServiceCloudProviderDept
          predicates:
            - Path=/getAll/**    #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET #只能时 GET 请求时，才能访问
      filters:
        - AddRequestParameter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为 X-Request-Id 值为 1024
        - PrefixPath=/dept #在请求路径前面加上 /dept

eureka:
  instance:
    instance-id: micro-service-cloud-gateway-9527
    hostname: micro-service-cloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/