server:
  port: 3344
spring:
  application:
    name: spring-cloud-config-center #服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yucaigit/-springcloud-config.git
          #仓库名
          search-paths:
            - springcloud-config
          force-pull: true # 如果Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
#          username: yucailei@126.com
#          password: LeiYucai0115.
      label: master

eureka:
  client: #将客户端注册到 eureka 服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/ #将服务注册到 Eureka 集群